---
name: rssguard

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-rssguard:
    name: "${{ matrix.os }}; webengine = ${{ matrix.use_webengine }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [windows-2019, ubuntu-16.04, macos-10.15]
        use_webengine: ["true", "false"]
        include:
          - os: windows-2019
            script_name: .\resources\scripts\github-actions\build-windows.ps1
          - os: ubuntu-16.04
            script_name: ./resources/scripts/github-actions/build-linux-mac.sh
          - os: macos-10.15
            script_name: ./resources/scripts/github-actions/build-linux-mac.sh
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Prepare environment and compile application
        run: ${{ matrix.script_name }} "${{ matrix.os }}" "${{ matrix.use_webengine }}"
      - name: Release assets
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: "Development builds"
          tag_name: "devbuild"
          body: "You can download RSS Guard development builds below. Latest dev. build was compiled from: $GITHUB_SHA"
          files: |
            .\rssguard-build\src\rssguard\*win64.exe
            .\rssguard-build\src\rssguard\*win64.zip
            ./rssguard-build/src/rssguard/rss*.AppImage
            ./rssguard-build/src/rssguard/rss*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}